steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${_ENV}',
         '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${REPO_NAME}:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}',
         '--memory', '128Mi',
         '--platform', 'managed',
         '--region', '${_REGION}',
         '--allow-unauthenticated',
         '--image', 'gcr.io/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA'
         ]

substitutions:
  _ENV: production
  _SERVICE_NAME: phish-ui
  _REGION: us-east1