steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA',
         '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag',
        'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA',
        'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}',
         '--memory', '128Mi',
         '--platform', 'managed',
         '--region', '${_REGION}',
         '--allow-unauthenticated',
         '--image', 'us-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}:$SHORT_SHA'
         ]

substitutions:
  _SERVICE_NAME: phish-ui
  _REGION: us-east1